version: '3.8'

services:
  frontend:
    container_name: cerberus-fe
    image: ${{ secrets.DOCKERHUB_USERNAME }}/cerberus-fe:latest
    ports:
      - "3000:80"
    restart: always

networks:
  default:
    name: web-network